apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}{{ .Values.nameSuffix }}
  namespace: showks
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: aggregator.stg.showks.containerdays.jp
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Chart.Name }}{{ .Values.nameSuffix }}
          servicePort: 8081
  - host: aggregator.prod.showks.containerdays.jp
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Chart.Name }}{{ .Values.nameSuffix }}
          servicePort: 8081
